#pragma once

enum class AssetType : int {
    NONE = -1,
    PLAYER,
    MAIN_MENU_BACKGROUND,
    GAME_BACKGROUND,
    SHIP,
    MAIN_MENU_PLAY_BUTTON,
    MAIN_MENU_LEADERBOARD_BUTTON,
    MAIN_MENU_EXIT_BUTTON
};
